### ISSUE TITLE
Read Data via API

### ISSUE THREAD

**Issue by clintonb-stripe** [openoakland/councilmatic#1]
This project currently uses a scraper to retrieve data. The City of Oakland's website runs on Legistar, which has an API that can be used instead.

- http://webapi.legistar.com/Home/Examples
- https://www.odata.org/getting-started/basic-tutorial/

Here is an example of requesting events, sorted with the latest event first.
- http://webapi.legistar.com/v1/oakland/events?$orderby=EventDate%20desc

Data can also be requested in JSON format by passing `'application/json'` in the `Accept` request header.

**Comment by clintonb** [comment]
Note that it seems some other Code for America projects make calls against Legistar APIs. It might be nice to identify/build a common API client.

https://www.odata.org/libraries/ might be a good place to start if we go the build route.

**Comment by hancush** [comment]
hey, there! datamade maintains [a python library for scraping both the legistar web interface and api](https://github.com/opencivicdata/python-legistar-scraper). maybe you'll find it useful. 🙃

we use it to scrape data for our own councilmatic instances. [here's our chicago scraper](https://github.com/opencivicdata/scrapers-us-municipal/blob/master/chicago). 

the folks over at [the city scrapers project](https://www.citybureau.org/city-scrapers) have also made use of it, specifically for events. [here's their chicago parks department scraper](https://github.com/City-Bureau/city-scrapers/blob/master/city_scrapers/spiders/chi_parks.py).
